[package]
name = "view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
model = { path = "../model" }

console_engine = "2.5.0"
project-root = "0.2.2"
